# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_auto_20170812_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='beer',
            new_name='product',
        ),
    ]
